version: '3'
services:
  myport:
    container_name: myport
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase: